
[plugins]

shadow = { id = "com.gradleup.shadow", version = "9.2.2" }
gitVersion = { id = "com.palantir.git-version", version = "4.1.0" }
spotless = { id = "com.diffplug.spotless", version = "8.0.0" }
buildconfig = { id = "com.github.gmazzo.buildconfig", version = "5.7.1" }
